// SPDX-License-Identifier: Apache-2.0

import { canonicalId, displayId, type EdgeFact, type ScanResult, type SymbolFact, type SymbolIdInput } from "./types.ts";

export function matches(symbol: SymbolFact, query: string, kind?: string, file?: string): boolean { const q=query.trim().toLowerCase(); if(kind&&symbol.kind.toLowerCase()!==kind.toLowerCase())return false; if(file&&!symbol.file.toLowerCase().includes(file.toLowerCase()))return false; return !q||[symbol.name,displayId(symbol.id),symbol.signature??"",symbol.file].some(v=>v.toLowerCase().includes(q)); }
export function symbolPreview(symbol: SymbolFact) { return {id:symbol.id,idDisplay:displayId(symbol.id),name:symbol.name,kind:symbol.kind,file:symbol.file,line:symbol.line,signature:symbol.signature??"",visibility:symbol.visibility??""}; }
export function resolveSymbols(result: ScanResult, query: string, exactId?: SymbolIdInput): SymbolFact[] { if(exactId !== undefined && (typeof exactId !== "string" || exactId.trim())) { try { const one=result.indexes.symbolByKey.get(canonicalId(exactId)); return one?[one]:[]; } catch { throw new TypeError("symbolId must be the lossless identity from a previous code2graph result"); } } return result.graph.symbols.filter(s=>matches(s,query)).sort((a,b)=>canonicalId(a.id).localeCompare(canonicalId(b.id))); }
export function edgesForSymbols(result: ScanResult,symbols:SymbolFact[],direction:"callers"|"callees",role?:string):EdgeFact[]{const set=new Map<string,EdgeFact>(); for(const s of symbols){const list=direction==="callers"?result.indexes.reverse.get(canonicalId(s.id)):result.indexes.forward.get(canonicalId(s.id));for(const edge of list??[])if(!role||edge.role.toLowerCase()===role.toLowerCase())set.set(`${canonicalId(edge.from)}>${canonicalId(edge.to)}:${edge.role}`,edge)}return [...set.values()].sort((a,b)=>canonicalId(a.from).localeCompare(canonicalId(b.from))||canonicalId(a.to).localeCompare(canonicalId(b.to)));}
export function edgePreview(edge:EdgeFact,result:ScanResult,direction:"callers"|"callees"){const id=direction==="callers"?edge.from:edge.to;const symbol=result.indexes.symbolByKey.get(canonicalId(id));return{role:edge.role,confidence:edge.confidence,provenance:edge.provenance,occurrence:edge.occ??null,other:symbol?symbolPreview(symbol):null};}
export function reverseImpact(result:ScanResult,targets:SymbolFact[],role:string|undefined,maxDepth:number,limit:number){const seen=new Set(targets.map(s=>canonicalId(s.id)));const out:Array<{depth:number;via:EdgeFact;symbol:SymbolFact|null}>=[];let frontier=[...seen];for(let depth=1;depth<=maxDepth&&frontier.length&&out.length<limit;depth++){const next:string[]=[];for(const key of frontier)for(const edge of result.indexes.reverse.get(key)??[]){if(role&&edge.role.toLowerCase()!==role.toLowerCase())continue;const from=canonicalId(edge.from);if(seen.has(from))continue;seen.add(from);next.push(from);out.push({depth,via:edge,symbol:result.indexes.symbolByKey.get(from)??null});if(out.length===limit)break;}frontier=next;}return out;}
