// SPDX-License-Identifier: Apache-2.0

import { Type } from "@earendil-works/pi-ai";
import { defineTool, keyHint } from "@earendil-works/pi-coding-agent";
import { Text } from "@earendil-works/pi-tui";
import { edgePreview, edgesForSymbols, matches, resolveSymbols, reverseImpact, symbolPreview } from "./relations.ts";
import { scan, summarize } from "./scan.ts";
import { DEFAULT_LIMIT, MAX_LIMIT, numberParam, refreshParam, rootParam, textResult, tierParam } from "./schema.ts";
const cap=(value:unknown, fallback:number, max=MAX_LIMIT)=>Math.max(1,Math.min(max,Math.floor(typeof value==="number"&&Number.isFinite(value)?value:fallback)));
function render(result:any,{expanded,isPartial}:any,theme:any){if(isPartial)return new Text(theme.fg("warning","Scanning code graph…"),0,0);const d=result.details??{};if(!expanded)return new Text(theme.fg("success",`✓ ${d.summary?.files??0} files • ${d.summary?.symbols??0} symbols • ${d.returned??d.count??0} results (${keyHint("app.tools.expand","expand")})`),0,0);return new Text(theme.fg("toolOutput",result.content[0]?.text??"Done"),0,0);}
async function get(ctx:any,p:any,signal:AbortSignal){return scan(ctx.cwd,p,signal);}
const symbolIdParam = Type.Optional(Type.Object({
  version: Type.Number({ description: "Lossless SymbolId wire version." }),
  scip: Type.String({ description: "SCIP identity rendering." }),
  lang: Type.Optional(Type.String({ description: "Global identity language." })),
  file: Type.Optional(Type.String({ description: "Local identity file." })),
}, { description: "Exact lossless SymbolId returned by code2graph_symbol_search." }));
function selector(p:any){if(p.symbolId&&typeof p.symbolId==="object")return;if(typeof p.query==="string"&&p.query.trim())return;throw new Error("Provide query or symbolId.");}
export const scanTool=defineTool({name:"code2graph_scan",label:"code2graph scan",description:"Scan source into deterministic structural facts. Use before name search or relation traversal.",parameters:Type.Object({root:rootParam(),tier:tierParam,maxFiles:numberParam("Maximum source files (hard cap 1000).",300,1,1000),includeHidden:Type.Optional(Type.Boolean({description:"Include hidden directories except safety-denylisted dependency/build directories.",default:false})),refresh:refreshParam()}),async execute(_:string,p:any,signal:AbortSignal,_u:any,ctx:any){const r=await get(ctx,p,signal);return textResult({summary:summarize(r),returned:r.graph.symbols.length});},renderResult:render});
export const symbolSearchTool=defineTool({name:"code2graph_symbol_search",label:"code2graph symbols",description:"Search definitions. Reuse returned lossless id values as symbolId for precise callers, callees, or impact queries.",parameters:Type.Object({query:Type.String({description:"Text matched against name, SCIP display, signature, or file."}),root:rootParam(),tier:tierParam,kind:Type.Optional(Type.String({description:"Exact kind filter."})),file:Type.Optional(Type.String({description:"File substring filter."})),limit:numberParam("Maximum results.",DEFAULT_LIMIT),refresh:refreshParam()}),async execute(_:string,p:any,signal:AbortSignal,_u:any,ctx:any){const r=await get(ctx,p,signal),all=r.graph.symbols.filter(s=>matches(s,p.query??"",p.kind,p.file));const limit=cap(p.limit,DEFAULT_LIMIT);return textResult({summary:summarize(r),returned:Math.min(limit,all.length),total:all.length,truncated:all.length>limit,symbols:all.slice(0,limit).map(symbolPreview)});},renderResult:render});
export function relationTool(name:string,label:string,direction:"callers"|"callees"){return defineTool({name,label,description:`Find ${direction}. Pass an exact lossless symbolId from code2graph_symbol_search to avoid ambiguous name matches.`,parameters:Type.Object({query:Type.Optional(Type.String({description:"Search text; ignored when symbolId is supplied."})),symbolId:symbolIdParam,root:rootParam(),tier:tierParam,role:Type.Optional(Type.String({description:"Exact edge role filter."})),limit:numberParam("Maximum edges.",DEFAULT_LIMIT),refresh:refreshParam()}),async execute(_:string,p:any,signal:AbortSignal,_u:any,ctx:any){selector(p);const r=await get(ctx,p,signal),symbols=resolveSymbols(r,p.query??"",p.symbolId),all=edgesForSymbols(r,symbols,direction,p.role),limit=cap(p.limit,DEFAULT_LIMIT);return textResult({summary:summarize(r),matchedSymbols:symbols.slice(0,10).map(symbolPreview),ambiguous:symbols.length>1,returned:Math.min(limit,all.length),total:all.length,truncated:all.length>limit,edges:all.slice(0,limit).map(e=>edgePreview(e,r,direction))});},renderResult:render});}
export const impactTool=defineTool({name:"code2graph_impact",label:"code2graph impact",description:"Compute bounded reverse-edge impact. Prefer an exact lossless symbolId for an unambiguous target.",parameters:Type.Object({query:Type.Optional(Type.String({description:"Target search text; ignored when symbolId is supplied."})),symbolId:symbolIdParam,root:rootParam(),tier:tierParam,role:Type.Optional(Type.String({description:"Exact edge role filter."})),maxDepth:numberParam("Maximum reverse traversal depth.",2,1,10),limit:numberParam("Maximum impacted symbols.",100,1,MAX_LIMIT),refresh:refreshParam()}),async execute(_:string,p:any,signal:AbortSignal,_u:any,ctx:any){selector(p);const r=await get(ctx,p,signal),targets=resolveSymbols(r,p.query??"",p.symbolId),all=reverseImpact(r,targets,p.role,cap(p.maxDepth,2,10),cap(p.limit,100));return textResult({summary:summarize(r),matchedTargets:targets.slice(0,10).map(symbolPreview),ambiguous:targets.length>1,returned:all.length,impacted:all.map(x=>({depth:x.depth,symbol:x.symbol?symbolPreview(x.symbol):null,via:edgePreview(x.via,r,"callers")}))});},renderResult:render});
