/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Resolve extracted facts into a code graph.
 *
 * `files` is a JS array of objects as returned by [`extract`]. `tier` selects
 * the resolver: `"name"` (default) uses Tier A (`NameOnly`); `"scope"` uses
 * Tier B (`Scoped`/`Exact`). Returns a JS object mirroring `CodeGraph`.
 */
export declare function buildGraph(files: any, tier?: string | undefined | null): any

/**
 * Extract symbols and references from a single source file.
 *
 * `file` is a project-relative path used to infer the language; `source` is
 * its contents. Returns a JS object mirroring `FileFacts`.
 */
export declare function extract(file: string, source: string): any

/**
 * Return the canonical language tag for a file path, or `null` if the
 * extension is not recognized (e.g. `"src/main.rs"` -> `"rust"`).
 */
export declare function languageOf(path: string): string | null
